server:
  port: 8888

welcome:
  message: Mkyong

driverClassName: org.sqlite.JDBC
url: jdbc:sqlite::resource:package/sample.db

spring:
  jpa:
    database-platform: com.jumia.config.SQLiteDialect
    hibernate:
      dialect: com.jumia.config.SQLiteDialect
      show-sql: true
      hbm2ddl:
        auto: create-drop
  thymeleaf:
    cache: false